// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyNO7ua75N-suAo7_raCNvPBROHh2Q48U',
    appId: '1:369523050218:web:def749e7f82ecd6dd37993',
    messagingSenderId: '369523050218',
    projectId: 'authtutorial-69e01',
    authDomain: 'authtutorial-69e01.firebaseapp.com',
    storageBucket: 'authtutorial-69e01.appspot.com',
    measurementId: 'G-ZDGP0V8TQ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPbYeUysNlwXIFIJUlVijjy5zlC5LvwaA',
    appId: '1:369523050218:android:e0ddc52e03cdf973d37993',
    messagingSenderId: '369523050218',
    projectId: 'authtutorial-69e01',
    storageBucket: 'authtutorial-69e01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhd_CJkQmtLtVG6KhkzEggaNUCzIharw0',
    appId: '1:369523050218:ios:11af0d571fba415bd37993',
    messagingSenderId: '369523050218',
    projectId: 'authtutorial-69e01',
    storageBucket: 'authtutorial-69e01.appspot.com',
    iosBundleId: 'com.example.apptutorial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhd_CJkQmtLtVG6KhkzEggaNUCzIharw0',
    appId: '1:369523050218:ios:0d757345527c2a14d37993',
    messagingSenderId: '369523050218',
    projectId: 'authtutorial-69e01',
    storageBucket: 'authtutorial-69e01.appspot.com',
    iosBundleId: 'com.example.apptutorial.RunnerTests',
  );
}
